package:
  name: nbtools
  version: 0.0.1

source:
  fn: 0.0.1.tar.gz
  url: https://github.com/28ni/nbtools/archive/0.0.1.tar.gz

build:
  number: 0

requirements:
  build:
    - python 2.7*
    - setuptools
  run:
    - python 2.7*

about:
  home: https://github.com/28ni/nbtools
  license: BSD
