package:
  name: nbtools
  version: 0.1.3

source:
  fn: 0.1.3.tar.gz
  url: https://github.com/28ni/nbtools/archive/0.1.3.tar.gz

build:
  number: 0

requirements:
  build:
    - setuptools
    - pip
    - python
    - jinja2
    - ipython-notebook 3.2*
    - matplotlib
    - ghdiff
    - nose
  run:
    - python
    - jinja2
    - ipython-notebook 3.2*
    - matplotlib
    - ghdiff
    - nose

test:
  commands:
    - nbvalidate --help
  requires:
    - python

about:
  home: https://github.com/28ni/nbtools
  license: BSD
